version: '3'

#source https://github.com/TribalScale/kafka-waffle-stack/blob/master/docker-compose.yml
#tutorial https://rmoff.net/2018/08/02/kafka-listeners-explained/

services:
  # ZooKeeper is a centralized service for maintaining configuration information,
  # naming, providing distributed synchronization, and providing group services.
  # It provides distributed coordination for our Kafka cluster.
  # http://zookeeper.apache.org/
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-cluster

  # Kafka is a distributed streaming platform. It is used to build real-time streaming
  # data pipelines that reliably move data between systems and platforms, and to build
  # real-time streaming applications that transform or react to the streams of data.
  # http://kafka.apache.org/
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "19092:19092"
    environment:
      #      KAFKA_ADVERTISED_HOST_NAME: kafka
      #      https://github.com/apache/kafka/blob/trunk/config/log4j.properties
      #      LOG4J_LOGGER_ORG_APACHE_KAFKA: DEBUG
      #      LOG4J_LOGGER_KAFKA: DEBUG
      #      LOG4J_LOGGER_KAFKA_REQUEST_LOGGER: DEBUG
      #      LOG4J_ROOTLOGGER: DEBUG
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092,PLAINTEXT://:19093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19092,PLAINTEXT://kafka:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 180000 #group.max.session.timeout.ms(default 30s)
      KAFKA_CREATE_TOPICS:
        #topic name : number of partitions : number of replicas.
        "executions:1:1,deposits:1:1"
#    volumes:
#      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-cluster
    depends_on:
      - zookeeper

networks:
  kafka-cluster:
    name: kafka-cluster-network
